# gz topic published by the JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/kuka_lwr/joint/arm_base_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/arm_base_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_0_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_0_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_1_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_2_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_3_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_3_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_4_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_4_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_5_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_5_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "model/kuka_lwr/joint/lwr_arm_6_joint/cmd_pos"
  gz_topic_name: "model/kuka_lwr/joint/lwr_arm_6_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
